### ISSUE TITLE
Regenerative No player healing

### ISSUE THREAD

**Issue by ArcaneEntity** [Jusey1/Jewelcraft#3]
playing on essential server 1.20.1 optifine and other mods which i dont see relevent but will provide if asked,

when on an amulet it doesn't heal ether the welder or nearby players at all, haven't been able to test with ring.

**Comment by Jusey1** [comment]
This is intentional.

**Comment by ArcaneEntity** [comment]
may i ask what it means when the description on modrinth describes:
"Regenerative: Heals **players**, animals, and villagers around the wearer."
key word being players.

**Comment by Jusey1** [comment]
I should fix that, thank you.
